### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tmooz**
Know Issue with showing up only after a (long) while.

Also adding the info how it could be set up in Home Assistant thx to @Exceptionfault

### CODE REVIEW

**Comment by skaterboy1990** [comment]
How Ro Install Witz hacs? I dont understand the Manual

**Comment by klaus1956** [comment]
I hope I understand your question right...
HACS is an extension that you can install using the Supervisor - look on Youtube for "how to install HACS" and you will find a lot of explenation videos.
When HACS is installed you can run it and install additional cummunity integrations on this extension.

**Comment by skaterboy1990** [comment]
Thx for the answer. I sucessfully installed senec with hacs. 
But i dont know how to configure it right now. Under hacs it is listed under inatalled but when i click on it it Shows only the Installation advices but IT also show the ability to reinstall so it is installed. Where to configure it right now so it shows me any information? Thx at all

**Comment by klaus1956** [comment]
After re-start of Home Assistant go to Integrations and call install new integration - now SENEC should be one of the available choices ( if I remember right)

**Comment by skaterboy1990** [comment]
I restarted homeasisstant and checked senec is installed via hacs but when i go to Integration and call new Integration senec is not listed there. Dont know why.

**Comment by klaus1956** [comment]
I remember that I had some problems too, but I do not remember how I solved it - sorry

**Comment by Pedddaaa** [comment]
Hi @ all i don´t understand how to install senec. i´ve installed hacs in HA but if i want to add Senec with hacs i cant find anything ?

**Comment by tmooz** [comment]
Be patient. Nobody seems to know why, but some of needed days and several restarts until it showed in integrations.
Also @mchwalisz could merge the request here after 3mo. 🥲

**Comment by mchwalisz** [comment]
Sorry for being inactive. Work kicked in harshly.

I'd much rather see a PR that would add the mentioned sensors to the integration itself. Just pointing to workaround does't bring good solutions.

**Pull request closed without merging**
