### PR TITLE
Update const.py for compatibility to HA core-2021.8.0

### PR DESCRIPTION
**Pull request by Dntouch**
https://github.com/mchwalisz/home-assistant-senec/issues/7

### CODE REVIEW

**Comment by Exceptionfault** [comment]
.. or remove the import of this const completely as it is not used in the script.

But anyways.. 👍

**Comment by Dntouch** [comment]
You are absolutely right. Removing it would be better and would not cause problems on previous HA versions.

**Comment by klaus1956** [comment]
This update is the onyl thing standing between me and HA 2021.8!
So a update is highly appreciated

**Comment by klaus1956** [comment]
Is there any way to change this myself as Mikolaj seems not te be active at the moment?

**Comment by Dntouch** [comment]
Hi Klaus,
you can install the Visual Studio Code Add-in and edit the const.py yourself.

After installation open the visual studio code editor and navigate to CONFIG -> custom_components -> senec -> const.py

edit line 4 to contain:

`from homeassistant.const import ENERGY_KILO_WATT_HOUR, PERCENTAGE, POWER_WATT`

**Comment by klaus1956** [comment]
Great - Thank You - this description was even working for me and 2021.8 is running  now :)

**Comment by klaus1956** [comment]
For integration in the new 2021.8-Energy appliction it seems that the entity types need to be updated ro "measuerment" .. but may be I am wrong

**Comment by Exceptionfault** [comment]
> For integration in the new 2021.8-Energy appliction it seems that the entity types need to be updated ro "measuerment" .. but may be I am wrong

Hi @klaus1956 ,

to problem is, that the sensors created by this plugin like for example the `sensor.senec_solar_generated_power` are of type "power in Watt". But the new energy feature of HA requires them to be of type "energy in kWh"

I've created 3 new sensors, using the [Riemann sum integral](https://www.home-assistant.io/integrations/integration/) plugin  in the `configuration.yaml`

```yaml
sensor:
  - platform: integration
    source: sensor.senec_solar_generated_power
    name: solar_generated_energy
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
  - platform: integration
    source: sensor.senec_grid_imported_power
    name: solar_imported_energy
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
  - platform: integration
    source: sensor.senec_grid_exported_power
    name: solar_exported_energy
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
```

**Comment by loeffelpan** [comment]
Any way to fork this integration an modify it for usage with energy app from HA 2021.8?
Workaround is fine, but a proper solution will be much better. But I do not have any skills in python to do this.

**Comment by klaus1956** [comment]
As we are discussing: I use data from this application to control a Wallbox PV- charging process. Is there a possibility for controlled entity update frequency ( e.g. all 30 sec).
I am nit sure which update frequency the IP interface provides.

**Comment by flyingrabbi** [comment]
Hey guys, i've just installed a v3 at home w/ battery. I also know next to nothing about github, linux and homeassistant haha.

Will be following this with interest, because as it stands, I'm like a little kid in the dark with a torch!

**Review by asommerms — APPROVED** [review]

**Comment by mchwalisz** [comment]
Thanks for looking into that.

**Pull request merged**
